### ISSUE TITLE
Depending on a global Quill

### ISSUE THREAD

**Issue by jancama2** [NoelOConnell/quill-image-uploader#1]
Hey there, a great quill module, thanks for it! 

**The problem**
One thing I ran into while developing an app with react in webpack: you depend on global Quill var to register the module to.

**Proposal**
Since you are using es6 import/export, wouldn't it make more sense to export the module and let the user to register the module? 

```
export  default ImageUploader;
```

```
import Quill from 'quill';
import ImageUploader 'quill-image-uploader';

Quill.register('module/imageUploader, ImageUploader)
```

**Note**
I can fork the repo and make PR if you dont have time but want the feature :).

**Comment by NoelOConnell** [comment]
Thank you for the suggestion.

I have released an updated version now which exports the module and does not depend on Quill.

You will now have to register the module after you import it.
I have updated the demo and readme to reflect the new usage changes.

**Comment by seekcx** [comment]
Hello, the current `blots/image` still has dependencies.
