### ISSUE TITLE
[feature request] Support upload image after drop or paste

### ISSUE THREAD

**Issue by mu-yu** [NoelOConnell/quill-image-uploader#12]
Please support upload image after paste action.

**Comment by NoelOConnell** [comment]
I did some work on this today.

There's a working version in this branch:
https://github.com/NoelOConnell/quill-image-uploader/tree/support-dropped-and-pasted-images

It needs some cross browser testing before merging into master.
Hopefully i'll get some time to look at that in the next few days.

**Comment by NoelOConnell** [comment]
Version 1.2.1 is released on npm now with support for pasted and dropped images.

**Comment by davidbludlow** [comment]
This still doesn't work in every case. See https://github.com/NoelOConnell/quill-image-uploader/issues/32 .
