### ISSUE TITLE
Handling resolving of the Image link

### ISSUE THREAD

**Issue by DvzH** [NoelOConnell/quill-image-uploader#13]
Hi,

After uploading image to the server. We get url of the img, So Instead of resolving it directly I wanted to send some extra information along with header in the GET request for the Image URL. How to do it ?

**Comment by NoelOConnell** [comment]
Hi there,

This plugin inserts an `img` tag into the editor. eg: `<img src="your-link" />`.
The browser is then handling the loading of the image.

Can you modify your request to use a query string?

**Comment by DvzH** [comment]
Yes.. I did it. It's working fine now. Just have one more question. I wanted to keep loader while image is being uploaded then resolved at the browser but sometimes, it's taking little bit more time. Is there a way to show the loader in the place where image is uploading in the editor and still allow user to modify the content of the editor ?
