### ISSUE TITLE
New Loader doesn't work in react quill

### ISSUE THREAD

**Issue by DvzH** [NoelOConnell/quill-image-uploader#16]
The recently released version doesn't show loader in React Quill Editor.

**Comment by NoelOConnell** [comment]
The loader is done with a CSS animation, did you include the css snippet in your code?

Does the image get uploaded correctly?

**Comment by DvzH** [comment]
Yeah.. CSS is already there. I am using it in React Quill Editor. Installed quill-image-uploader using npm. Do I need to import CSS manually ?

**Comment by NoelOConnell** [comment]
This module includes [default CSS](https://github.com/NoelOConnell/quill-image-uploader/blob/master/dist/quill.imageUploader.min.css) for the loading effect.

You need to include that also in your code if you want the loading effect.
The other option is to add your own CSS for a different loading style.

You can copy the contents of the CSS file above and put it into the CSS for your page.

**Comment by DvzH** [comment]
Okay will try both ways. thanks for your reply
