### ISSUE TITLE
I don't know how to make this module work in React Quill

### ISSUE THREAD

**Issue by yonimor** [NoelOConnell/quill-image-uploader#17]
Hello, first of all thanks for this module.

I know this is probably not the right place for this - but can you please refer me to an example of implementing this module with React-Quill?

Thanks in advance.

**Comment by NoelOConnell** [comment]
What version of react-quill are you using?

You should be able to import it and add it to the `modules` prop in React

**Comment by yonimor** [comment]
Managed to make it work, thanks.

**Comment by mmabraham** [comment]
In case this helps anyone,  here is how I've implemented it with react-quill:

```
import React from 'react';
import 'react-quill/dist/quill.snow.css';
import ImageUploader from "quill-image-uploader";
import ReactQuill, { Quill } from 'react-quill';

import { uploadFile } from '../api';

Quill.register("modules/imageUploader", ImageUploader);

const modules = {
    toolbar: [
        [ 'image'],
    ],
    imageUploader: {
        upload: file => uploadFile(file).then(({ url }) => url),
    },
}
const ContentEditor = ({ content, onContentChange }) => {
    return <ReactQuill
        defaultValue={content}
        onChange={onContentChange}
        modules={modules}
        theme="snow"
    />
}

export default ContentEditor;
```

**Comment by NoelOConnell** [comment]
Thanks @mmabraham 

I've added a react-quill example in the readme.
There's a link to a [codesandbox](https://codesandbox.io/s/react-quill-demo-qr8xd)

If you are passing custom `formats` to the react-quill editor then you need to add `"imageBlot"` to the array of formats.
