### ISSUE TITLE
Drag and Drop of image in react quill editor always appends it at the end of the line instead of current cursor position.

### ISSUE THREAD

**Issue by DvzH** [NoelOConnell/quill-image-uploader#18]

**Comment by NoelOConnell** [comment]
Can you provide a link to an example so I can reproduce this?

I tried this in on the demo and the image appended in the correct cursor position.

**Comment by DvzH** [comment]
It is working like a charm once I defined my modules and formats inside editor component. thank for the wonderful library

**Comment by jaddoescad** [comment]
How did you fix it? I'm having the same issue, I even tested it on the react example provided, and drag and drop does not work, it just focuses at the end
