### ISSUE TITLE
Uploading images in between words/letters causes trimming of characters in react-quill editor

### ISSUE THREAD

**Issue by DvzH** [NoelOConnell/quill-image-uploader#19]
When we try to upload the image in between words or letters in ReactQuill Editor, after Image upload it trims 3 characters exactly every time in the editor and it is replaced by Image.

**Comment by NoelOConnell** [comment]
I've added a react-quill example in the readme.
There's a link to a [codesandbox](https://codesandbox.io/s/react-quill-demo-qr8xd)

If you are passing custom `formats` to the react-quill editor then you need to add `"imageBlot"` to the array of formats.

**Comment by DvzH** [comment]
@NoelOConnell Thanks for replying. I had defined modules and formats outside editor component because of that it was breaking this binding when I defined them inside editor component. It is working fine. Thank you for the wondeful library.
