### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by nring** [NoelOConnell/quill-image-uploader#2]
Thanks for the Quill module! 

We noticed that the image upload functionality didn't work in our application nor the demo file. I haven't been able to figure out why as we're transpiling everything on our end. I was able to trace IE11's execution all the way up to line 28 in `quill.imageUploader.js`: 
```
   this.fileHolder.click();
```

After this line, nothing else executes. I considered that IE11 might have trouble programmatically clicking a file input element, but I saw this same functionality working in some other examples. Any ideas?

**Comment by NoelOConnell** [comment]
Hi,

IE 11 does not support Promises, do you have a polyfill included for Promises?
The demo file works for me in IE 11, once I included a Promises polyfill the demo runs.

I ran `npm start` from the root folder and navigated to the demo.html file.

Do you have any console logs or errors that might be helpful?

**Comment by nring** [comment]
Unfortunately the console isn't generating anything at all; no errors, no warnings.

How are you including your polyfill? We have a project-wide polyfill included with `@babel/polyfill` and we're using Promises successfully elsewhere in our project.

**Comment by NoelOConnell** [comment]
I released an update version that wraps `this.fileHolder.click()` inside a `requestAnimationFrame` callback.
I have used this technique in previous projects so it might work in this situation.

Could you update to the latest version 1.0.1 and see if that resolves your issue.

**Comment by nring** [comment]
Thanks for the update, I hadn't seen that technique before. It looks like it fixes the IE11 issue but Chrome stopped working now. Firefox, Safari, and Edge still work though. I tried re-adding the `this.fileHolder.click()` line outside of the requestAnimationFrame callback which re-enabled support on Chrome, but it caused the file select window to appear twice on Edge. Any other suggestions?

**Comment by NoelOConnell** [comment]
@nring I've released 1.0.2 version now.

I've tested it in Chrome, Firefox, Edge and IE 11.
It resolves the issue you described with the file window not opening in Chrome.

**Comment by nring** [comment]
@NoelOConnell This fixes it in everything I've tested so far. Thanks for implementing!
