### ISSUE TITLE
Still showing base64 based image when pasting from image file

### ISSUE THREAD

**Issue by Ibrahimsyah** [NoelOConnell/quill-image-uploader#22]
I trying to copy-paste my image from computer (local file) as shown below to editor
![image](https://user-images.githubusercontent.com/7591715/84292890-31993600-ab71-11ea-8e00-9c051b5d916d.png)

but it still parsed as base64 string
![image](https://user-images.githubusercontent.com/7591715/84293077-7f15a300-ab71-11ea-9037-3a57b2b82fc9.png)

**Comment by oldner** [comment]
@Ibrahimsyah did you fix it?
