### ISSUE TITLE
allow the ability to drag and drop images from the web

### ISSUE THREAD

**Issue by jaddoescad** [NoelOConnell/quill-image-uploader#23]
everything seems to work fine, however once I install this library, i am no longer able to drag images from the web. 

so if i go on google images and drag and drop and image into the editor, it will not work.

**Comment by NoelOConnell** [comment]
Does this only happen with images dragged from the web?

Does it work if you drag an image from the local file system?

**Comment by MortezaT** [comment]
@NoelOConnell 
Since you prevent default on any drop there is no chance for other plugins (or even quill) to handle that event
I think you should check if there is no previous drag start on component first otherwise the arena is all yours ;)

**Comment by MortezaT** [comment]
I created you a [pull request](https://github.com/NoelOConnell/quill-image-uploader/pull/30) that may help with this issue

**Comment by shyamal890** [comment]
@NoelOConnell any chance allowing this?
