### ISSUE TITLE
"Global CSS cannot be imported from within node_modules." error in Next.js with react-quill

### ISSUE THREAD

**Issue by artuncolak** [NoelOConnell/quill-image-uploader#26]
I have this issue when using quill-image-uploader with react-quill & next.js

![Annotation 2020-07-06 192549](https://user-images.githubusercontent.com/26934091/86616457-87b99780-bfbe-11ea-9cb6-02448d3c201b.png)

**Comment by chrysb** [comment]
Having the same issue

**Comment by artuncolak** [comment]
@chrysb 
I find [this](https://github.com/quilljs/quill/issues/1089#issuecomment-319567957) solution for uploading images directly to server with custom image handler without quill-image-uploader and it works with next js. You can use it until this issue solved.

**Comment by chrysb** [comment]
> @chrysb
> I find [this](https://github.com/quilljs/quill/issues/1089#issuecomment-319567957) solution for uploading images directly to server with custom image handler without quill-image-uploader and it works with next js. You can use it until this issue solved.

Thank you!

**Comment by deathemperor** [comment]
> @chrysb
> I find [this](https://github.com/quilljs/quill/issues/1089#issuecomment-319567957) solution for uploading images directly to server with custom image handler without quill-image-uploader and it works with next js. You can use it until this issue solved.

not sure how to apply it into nextjs, can you elaborate?

**Comment by lakindu2002** [comment]
is there a way to use this library?
