### ISSUE TITLE
Text removed

### ISSUE THREAD

**Issue by paullaffitte** [NoelOConnell/quill-image-uploader#5]
Hello,

In some cases, inserting an image remove some text after the image. For example if i try to insert an image between two word, the second word will disappears. I think it's related to the `insertToEditor` function that call `this.quill.deleteText(range.index, 2);` to delete the placeholder image.

Thanks

**Comment by NoelOConnell** [comment]
Hi,

I released an update which I believe fixes the problem. 
Can you try version 1.1.0 and confirm that this issue is fixed for you now?

**Comment by paullaffitte** [comment]
I confirm that it fixed the issue, thanks!
