### ISSUE TITLE
Upload seems to loop forever when it fails

### ISSUE THREAD

**Issue by paullaffitte** [NoelOConnell/quill-image-uploader#6]
Hello,

When I make an upload fail (for instance the file uploaded is too big), the placeholder image will stay with the loading animation. I can take care myself of the user notification and I think it should be the case for everybody, but I would like the placeholder image to be removed if the upload didn't worked.

Thanks

**Comment by NoelOConnell** [comment]
Hi,

I have released an update today which will remove the placeholder image if the Promise is rejected.
Version 1.1.0

**Comment by paullaffitte** [comment]
It seems that it works like a charm, thanks!
