### ISSUE TITLE
paste upload broken on chromuim 104.0.1293.47

### ISSUE THREAD

**Issue by woshiguabi** [NoelOConnell/quill-image-uploader#61]
open the example codesandbox and just paste a image.
https://codesandbox.io/s/mutable-tdd-lrsvh?file=/index.html
![image](https://user-images.githubusercontent.com/17465858/184309866-bb0065ae-c1d4-4515-ab79-c81f01a042db.png)

https://github.com/NoelOConnell/quill-image-uploader/blob/98907e3af69730c2bc5a9d1d9da59c4ac5f486a0/src/quill.imageUploader.js#L99-L102

`this.quill.getSelection()` returns null, but works well on chromuim 102.0.5005.115

**Comment by gozeon** [comment]
![image](https://user-images.githubusercontent.com/17582116/184784979-0fec9a4b-2551-41e0-81c5-3a06f29a8cdc.png)
same error

**Comment by NoelOConnell** [comment]
Released and fixed with #63 
npm version 1.2.3

**Comment by agoncharov-reef** [comment]
I think you should update `dist` folder, cause currently `dist/quill.imageUploader.min.js` does not contain the patch.
