### ISSUE TITLE
How to cancel upload if image is oversize?

### ISSUE THREAD

**Issue by mu-yu** [NoelOConnell/quill-image-uploader#9]
I have tried to reject the promise, but it still upload the picture with base64 string.

**Comment by mu-yu** [comment]
I have debuged the code of this plugin, and found that filereader `load` event is happened after `removeBase64Image` function in error handler.

**Comment by NoelOConnell** [comment]
PR merged now.

Version 1.1.1 is released on NPM now with those changes.

:+1:
